version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    networks:
      - bancos
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rl321@!
      - POSTGRES_DB=postgres
    volumes:
      - ../postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - bancos
networks:
  bancos:
    driver: bridge
    ipam:
      config:
      - subnet: 127.0.0.1/24